"""Voice Studio: text-to-voiceover generation (Premium-style, local-first).

Two engines:
  edge  - Microsoft Edge neural voices via edge-tts (300+ voices/accents,
          needs internet, no account or key). Produces MP3.
  piper - Fully-offline neural TTS. Voice models (~60MB) download once from
          Hugging Face into %LOCALAPPDATA%/Corvus/piper-voices and then run
          on CPU with no network. Produces WAV.

Long texts are split into sentences with the same SentenceChunker the live
voice pipeline uses, synthesized sequentially (gentle on CPU/commit), and the
segments concatenated: MP3 frames concatenate cleanly; Piper PCM is joined
and wrapped in a single WAV header.
"""

from __future__ import annotations

import io
import re
import wave
from dataclasses import dataclass
from pathlib import Path

import structlog

from ..config import data_dir

log = structlog.get_logger("corvus")

MAX_TEXT_CHARS = 20_000

# Preview sentences per language, so auditioning a voice speaks its own
# language instead of stumbling through English.
PREVIEW_TEXTS = {
    "en": "Hello! This is a preview of my voice, generated by Corvus.",
    "hi": "नमस्ते! यह मेरी आवाज़ का एक नमूना है, जो कोरवस ने बनाया है।",
    "de": "Hallo! Dies ist eine Vorschau meiner Stimme, erstellt von Corvus.",
    "fr": "Bonjour ! Voici un aperçu de ma voix, généré par Corvus.",
    "es": "¡Hola! Esta es una muestra de mi voz, generada por Corvus.",
    "it": "Ciao! Questa è un'anteprima della mia voce, generata da Corvus.",
    "pt": "Olá! Esta é uma amostra da minha voz, gerada pelo Corvus.",
    "zh": "你好！这是我的声音预览，由 Corvus 生成。",
    "ja": "こんにちは！これは Corvus が生成した私の声のプレビューです。",
    "ko": "안녕하세요! 이것은 Corvus가 생성한 제 목소리의 미리듣기입니다.",
    "ar": "مرحباً! هذه معاينة لصوتي، من إنشاء كورفوس.",
    "ru": "Привет! Это образец моего голоса, созданный Corvus.",
    "tr": "Merhaba! Bu, Corvus tarafından oluşturulan sesimin bir önizlemesi.",
    "ur": "السلام علیکم! یہ میری آواز کا نمونہ ہے، جو کورवس نے بنایا ہے۔",
    "bn": "নমস্কার! এটি আমার কণ্ঠের একটি নমুনা, কর্ভাস দ্বারা তৈরি।",
    "ta": "வணக்கம்! இது கார்வஸ் உருவாக்கிய என் குரலின் மாதிரி.",
    "te": "నమస్కారం! ఇది కార్వస్ రూపొందించిన నా స్వరం యొక్క నమూనా.",
}
PREVIEW_TEXT = PREVIEW_TEXTS["en"]


def preview_text_for(voice_id: str) -> str:
    """Pick the preview sentence matching a voice's language.

    Edge ids look like "hi-IN-SwaraNeural", Piper ids like "hi_IN-pratham-medium".
    """
    lang = re.split(r"[-_]", voice_id, maxsplit=1)[0].lower()
    return PREVIEW_TEXTS.get(lang, PREVIEW_TEXT)

# Voices are synthesized sentence-per-request; very long sentences are fine,
# but chunking keeps memory flat and lets errors surface early.
_HF_BASE = "https://huggingface.co/rhasspy/piper-voices/resolve/main"


@dataclass(frozen=True)
class PiperVoiceInfo:
    id: str          # e.g. "en_US-amy-medium"
    label: str       # human name
    language: str    # e.g. "English (US)"
    gender: str
    size_mb: int

    @property
    def hf_path(self) -> str:
        lang, name, quality = self.id.split("-", 2)
        family = lang.split("_")[0]
        return f"{_HF_BASE}/{family}/{lang}/{name}/{quality}/{self.id}"


# Curated offline catalog: every entry verified to exist in rhasspy/piper-voices.
PIPER_CATALOG: list[PiperVoiceInfo] = [
    PiperVoiceInfo("en_US-amy-medium", "Amy", "English (US)", "Female", 61),
    PiperVoiceInfo("en_US-lessac-medium", "Lessac", "English (US)", "Female", 61),
    PiperVoiceInfo("en_US-ryan-high", "Ryan", "English (US)", "Male", 115),
    PiperVoiceInfo("en_US-kristin-medium", "Kristin", "English (US)", "Female", 61),
    PiperVoiceInfo("en_US-joe-medium", "Joe", "English (US)", "Male", 61),
    PiperVoiceInfo("en_GB-alan-medium", "Alan", "English (UK)", "Male", 61),
    PiperVoiceInfo("en_GB-cori-high", "Cori", "English (UK)", "Female", 115),
    PiperVoiceInfo("en_GB-alba-medium", "Alba", "English (UK, Scottish)", "Female", 61),
    PiperVoiceInfo("de_DE-thorsten-medium", "Thorsten", "German", "Male", 61),
    PiperVoiceInfo("fr_FR-siwis-medium", "Siwis", "French", "Female", 61),
    PiperVoiceInfo("es_ES-davefx-medium", "DaveFX", "Spanish", "Male", 61),
    PiperVoiceInfo("hi_IN-pratham-medium", "Pratham", "Hindi", "Male", 61),
]
_PIPER_BY_ID = {v.id: v for v in PIPER_CATALOG}


# Sentence boundaries across scripts: Western .!?…, CJK 。！？, Devanagari
# danda ।॥, Arabic ؟۔, Ethiopic ።. Whitespace after is optional because CJK
# text has none.
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?…。！？।॥؟۔።])\s*")
# One Edge request per ~4000 chars keeps prosody natural (the voice reads
# whole passages, not stitched single sentences) while bounding request size.
_BATCH_CHARS = 4000


def _batches(text: str) -> list[str]:
    """Split long text into few large passages on sentence boundaries."""
    text = text.strip()
    if len(text) <= _BATCH_CHARS:
        return [text] if text else []
    sentences = [s for s in _SENTENCE_SPLIT.split(text) if s.strip()]
    batches: list[str] = []
    current = ""
    for sentence in sentences:
        if current and len(current) + len(sentence) + 1 > _BATCH_CHARS:
            batches.append(current)
            current = sentence
        else:
            current = f"{current} {sentence}".strip() if current else sentence
        # A single huge "sentence" (no recognized punctuation) is cut hard.
        while len(current) > _BATCH_CHARS:
            batches.append(current[:_BATCH_CHARS])
            current = current[_BATCH_CHARS:]
    if current:
        batches.append(current)
    return batches


# -- Edge engine ---------------------------------------------------------------

_edge_catalog: list[dict] | None = None


async def edge_voices() -> list[dict]:
    """Full Edge voice catalog, cached for the app's lifetime. Empty when offline."""
    global _edge_catalog
    if _edge_catalog is None:
        try:
            import edge_tts

            raw = await edge_tts.list_voices()
            _edge_catalog = [
                {
                    "id": v["ShortName"],
                    "name": v["ShortName"].split("-")[-1].removesuffix("Neural"),
                    "locale": v["Locale"],
                    "gender": v["Gender"],
                }
                for v in raw
            ]
        except Exception as exc:
            log.warning("studio_edge_catalog_failed", error=str(exc))
            return []
    return _edge_catalog


def _pct(value: int) -> str:
    return f"{value:+d}%"


async def synthesize_edge(
    text: str, voice: str, rate: int = 0, pitch: int = 0, volume: int = 0
) -> bytes:
    """Synthesize with an Edge neural voice; rate/volume in ±%, pitch in ±Hz."""
    import edge_tts

    out = bytearray()
    for chunk in _batches(text):
        communicate = edge_tts.Communicate(
            chunk, voice=voice, rate=_pct(rate), pitch=f"{pitch:+d}Hz", volume=_pct(volume)
        )
        async for part in communicate.stream():
            if part["type"] == "audio":
                out.extend(part["data"])
    if not out:
        raise RuntimeError("Edge returned no audio (offline or invalid voice?)")
    return bytes(out)


# -- Piper engine --------------------------------------------------------------

def piper_dir() -> Path:
    d = data_dir() / "piper-voices"
    d.mkdir(parents=True, exist_ok=True)
    return d


def piper_installed() -> list[str]:
    return sorted(
        p.stem for p in piper_dir().glob("*.onnx")
        if p.with_suffix(".onnx.json").exists() and p.stem in _PIPER_BY_ID
    )


def piper_catalog() -> list[dict]:
    installed = set(piper_installed())
    return [
        {
            "id": v.id,
            "name": v.label,
            "language": v.language,
            "gender": v.gender,
            "size_mb": v.size_mb,
            "installed": v.id in installed,
        }
        for v in PIPER_CATALOG
    ]


async def piper_download(voice_id: str) -> None:
    """Fetch a voice's .onnx + .onnx.json from Hugging Face (one-time)."""
    info = _PIPER_BY_ID.get(voice_id)
    if info is None:
        raise ValueError(f"unknown Piper voice: {voice_id}")
    import httpx

    async with httpx.AsyncClient(follow_redirects=True, timeout=600) as client:
        for suffix in (".onnx", ".onnx.json"):
            dest = piper_dir() / f"{voice_id}{suffix}"
            if dest.exists():
                continue
            url = f"{info.hf_path}{suffix}"
            tmp = dest.with_suffix(dest.suffix + ".part")
            async with client.stream("GET", url) as response:
                response.raise_for_status()
                with open(tmp, "wb") as f:
                    async for block in response.aiter_bytes(1024 * 256):
                        f.write(block)
            tmp.rename(dest)
    log.info("studio_piper_voice_installed", voice=voice_id)


_piper_loaded: dict[str, object] = {}


def _piper_voice(voice_id: str):
    if voice_id not in _piper_loaded:
        from piper import PiperVoice

        model = piper_dir() / f"{voice_id}.onnx"
        if not model.exists():
            raise FileNotFoundError(
                f"Piper voice '{voice_id}' is not installed - download it first"
            )
        _piper_loaded[voice_id] = PiperVoice.load(str(model))
    return _piper_loaded[voice_id]


def _synthesize_piper_sync(text: str, voice_id: str, rate: int = 0, volume: int = 0) -> bytes:
    """Piper CPU synthesis to one WAV; piper handles sentence splitting itself."""
    from piper import SynthesisConfig

    voice = _piper_voice(voice_id)
    config = SynthesisConfig(
        # +25% speed => shorter audio => length_scale 1/1.25.
        length_scale=1.0 / (1.0 + rate / 100.0) if rate else None,
        volume=max(0.0, 1.0 + volume / 100.0),
    )
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wav:
        voice.synthesize_wav(text, wav, syn_config=config)
    return buf.getvalue()


async def synthesize_piper(text: str, voice_id: str, rate: int = 0, volume: int = 0) -> bytes:
    import asyncio

    return await asyncio.to_thread(_synthesize_piper_sync, text, voice_id, rate, volume)


# -- Shared entry point --------------------------------------------------------

def voiceovers_dir() -> Path:
    d = data_dir() / "voiceovers"
    d.mkdir(parents=True, exist_ok=True)
    return d


async def synthesize(
    engine: str, text: str, voice: str, rate: int = 0, pitch: int = 0, volume: int = 0
) -> tuple[bytes, str]:
    """Returns (audio bytes, file extension) for the requested engine."""
    if engine == "edge":
        return await synthesize_edge(text, voice, rate, pitch, volume), "mp3"
    if engine == "piper":
        return await synthesize_piper(text, voice, rate, volume), "wav"
    raise ValueError(f"unknown engine: {engine}")
